### PR TITLE
More up/down variations

### PR DESCRIPTION
**Pull request by francescobrivio**
Some fixes in the up/down variations:
- initialize (to `-999`) the VBF up/down variables

### CODE REVIEW

**Comment by francescobrivio** [comment]
@camendola just to let you know I've opened this new PR. Please have a look.

Sill missing:
- total JES variation
- initialization of VBFjj_deltaEta and VBFjj_mass

**Comment by camendola** [comment]
thanks, looks ok to me!

**Comment by francescobrivio** [comment]
Do you think `VBFjj_deltaEta` and `VBFjj_mass` should be initialized as well? 
I think not, because they are used in the selections **only if** `isVBF==1`. So they should not give the same error as for the `VBF_pT` and 'VBF_mass' variables (i.e. the vector is empty and when you try to access it the program crashes)... but maybe I'm missing something!

**Comment by camendola** [comment]
"because they are used in the selections only if `isVBF==1`" -> uhm I don't think that's true, the selections are usually in the form `isVBF == 1 && VBFjj_deltaEta > X && VBFjj_mass > Y`, but I'm not sure if this matters to your code.
Besides, VBFjj quantities are probably going to be needed as inputs to DNNs, right? Does this matter? I guess yes, the code should access an underflow in that case if there's no VBF pair

**Comment by francescobrivio** [comment]
I added the total JES variation shifts.
@camendola can you have a look at this last commit (https://github.com/francescobrivio/KLUBAnalysis/pull/13/commits/3c13cf7ac899713cb7755616d8947463588ecfb8) ? 
If all it's ok for you, I will propagate it to 2017 and 2018 as well.

**Comment by francescobrivio** [comment]
The function `getShiftedMET_jet` does not have the uncertainty `jets_jetUncRegrouped_Total_up\down`. Also, it returns a vector while I need a single value, it seemed easier to rewrite the function for the total uncertainty.

**Comment by francescobrivio** [comment]
Added initialization of `VBFjj_mass` variable. I also realized there is no up/down variations for the `VBFjj_deltaEta` variable, so no problem there.

**Comment by camendola** [comment]
> I also realized there is no up/down variations for the `VBFjj_deltaEta` variable, so no problem there.

OK right

**Comment by camendola** [comment]
OK for the rest

**Comment by francescobrivio** [comment]
Propagated JES variation shifts to 2017 and 2018 skimmers.

**Comment by francescobrivio** [comment]
Added the total JES variations in the new module

**Comment by francescobrivio** [comment]
@camendola waiting for your final approval before merging

**Comment by camendola** [comment]
I went through it and it looks ok. Just one doubt: should also the vectors of bjets up/down uncertainties be initialized? or is it protected because you always require at least 2 bjets?

**Comment by francescobrivio** [comment]
> I went through it and it looks ok. Just one doubt: should also the vectors of bjets up/down uncertainties be initialized? or is it protected because you always require at least 2 bjets?

Yeah I always ask at least two bjets otherwise all the BDT and DNN values can not be computed (especially the DNN crashes I think), so we should be safe there.

**Comment by camendola** [comment]
ok, then you have my blessing to merge

**Pull request merged**
